/*
 Navicat Premium Data Transfer

 Source Server         : eBipani
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : localhost:1521
 Source Schema         : C##EBIPANI

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 23/02/2022 00:00:25
*/


-- ----------------------------
-- Table structure for AUTH_GROUP
-- ----------------------------
DROP TABLE "C##EBIPANI"."AUTH_GROUP";
CREATE TABLE "C##EBIPANI"."AUTH_GROUP" (
  "ID" NUMBER(11,0) VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_78612".nextval NOT NULL,
  "NAME" NVARCHAR2(150) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of AUTH_GROUP
-- ----------------------------

-- ----------------------------
-- Table structure for AUTH_GROUP_PERMISSIONS
-- ----------------------------
DROP TABLE "C##EBIPANI"."AUTH_GROUP_PERMISSIONS";
CREATE TABLE "C##EBIPANI"."AUTH_GROUP_PERMISSIONS" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_78616".nextval NOT NULL,
  "GROUP_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "PERMISSION_ID" NUMBER(11,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of AUTH_GROUP_PERMISSIONS
-- ----------------------------

-- ----------------------------
-- Table structure for AUTH_PERMISSION
-- ----------------------------
DROP TABLE "C##EBIPANI"."AUTH_PERMISSION";
CREATE TABLE "C##EBIPANI"."AUTH_PERMISSION" (
  "ID" NUMBER(11,0) VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_78609".nextval NOT NULL,
  "NAME" NVARCHAR2(255) VISIBLE,
  "CONTENT_TYPE_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "CODENAME" NVARCHAR2(100) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of AUTH_PERMISSION
-- ----------------------------
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('1', 'Can add log entry', '1', 'add_logentry');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('2', 'Can change log entry', '1', 'change_logentry');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('3', 'Can delete log entry', '1', 'delete_logentry');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('4', 'Can view log entry', '1', 'view_logentry');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('5', 'Can add permission', '2', 'add_permission');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('6', 'Can change permission', '2', 'change_permission');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('7', 'Can delete permission', '2', 'delete_permission');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('8', 'Can view permission', '2', 'view_permission');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('9', 'Can add group', '3', 'add_group');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('10', 'Can change group', '3', 'change_group');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('11', 'Can delete group', '3', 'delete_group');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('12', 'Can view group', '3', 'view_group');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('13', 'Can add user', '4', 'add_user');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('14', 'Can change user', '4', 'change_user');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('15', 'Can delete user', '4', 'delete_user');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('16', 'Can view user', '4', 'view_user');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('17', 'Can add content type', '5', 'add_contenttype');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('18', 'Can change content type', '5', 'change_contenttype');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('19', 'Can delete content type', '5', 'delete_contenttype');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('20', 'Can view content type', '5', 'view_contenttype');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('21', 'Can add session', '6', 'add_session');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('22', 'Can change session', '6', 'change_session');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('23', 'Can delete session', '6', 'delete_session');
INSERT INTO "C##EBIPANI"."AUTH_PERMISSION" VALUES ('24', 'Can view session', '6', 'view_session');

-- ----------------------------
-- Table structure for AUTH_USER
-- ----------------------------
DROP TABLE "C##EBIPANI"."AUTH_USER";
CREATE TABLE "C##EBIPANI"."AUTH_USER" (
  "ID" NUMBER(11,0) VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_78619".nextval NOT NULL,
  "PASSWORD" NVARCHAR2(128) VISIBLE,
  "LAST_LOGIN" TIMESTAMP(6) VISIBLE,
  "IS_SUPERUSER" NUMBER(1,0) VISIBLE NOT NULL,
  "USERNAME" NVARCHAR2(150) VISIBLE,
  "FIRST_NAME" NVARCHAR2(150) VISIBLE,
  "LAST_NAME" NVARCHAR2(150) VISIBLE,
  "EMAIL" NVARCHAR2(254) VISIBLE,
  "IS_STAFF" NUMBER(1,0) VISIBLE NOT NULL,
  "IS_ACTIVE" NUMBER(1,0) VISIBLE NOT NULL,
  "DATE_JOINED" TIMESTAMP(6) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of AUTH_USER
-- ----------------------------

-- ----------------------------
-- Table structure for AUTH_USER_GROUPS
-- ----------------------------
DROP TABLE "C##EBIPANI"."AUTH_USER_GROUPS";
CREATE TABLE "C##EBIPANI"."AUTH_USER_GROUPS" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_78623".nextval NOT NULL,
  "USER_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "GROUP_ID" NUMBER(11,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of AUTH_USER_GROUPS
-- ----------------------------

-- ----------------------------
-- Table structure for AUTH_USER_USER_PERMISSIONS
-- ----------------------------
DROP TABLE "C##EBIPANI"."AUTH_USER_USER_PERMISSIONS";
CREATE TABLE "C##EBIPANI"."AUTH_USER_USER_PERMISSIONS" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_78626".nextval NOT NULL,
  "USER_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "PERMISSION_ID" NUMBER(11,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of AUTH_USER_USER_PERMISSIONS
-- ----------------------------

-- ----------------------------
-- Table structure for CATEGORY
-- ----------------------------
DROP TABLE "C##EBIPANI"."CATEGORY";
CREATE TABLE "C##EBIPANI"."CATEGORY" (
  "CATEGORY_NAME" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "DESCRIPTION" VARCHAR2(256 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CATEGORY
-- ----------------------------
INSERT INTO "C##EBIPANI"."CATEGORY" VALUES ('Electronic Devices', NULL);
INSERT INTO "C##EBIPANI"."CATEGORY" VALUES ('Groceries', NULL);
INSERT INTO "C##EBIPANI"."CATEGORY" VALUES ('Home & Lifestyle', NULL);
INSERT INTO "C##EBIPANI"."CATEGORY" VALUES ('Fashion', NULL);
INSERT INTO "C##EBIPANI"."CATEGORY" VALUES ('Home Appliances', NULL);
INSERT INTO "C##EBIPANI"."CATEGORY" VALUES ('Sports & Outdoor', NULL);

-- ----------------------------
-- Table structure for CUSTOMER
-- ----------------------------
DROP TABLE "C##EBIPANI"."CUSTOMER";
CREATE TABLE "C##EBIPANI"."CUSTOMER" (
  "EMAIL" VARCHAR2(320 BYTE) VISIBLE NOT NULL,
  "FIRST_NAME" VARCHAR2(64 BYTE) VISIBLE,
  "SECOND_NAME" VARCHAR2(64 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of CUSTOMER
-- ----------------------------
INSERT INTO "C##EBIPANI"."CUSTOMER" VALUES ('s@gmail.com', 'ab', 'dc');
INSERT INTO "C##EBIPANI"."CUSTOMER" VALUES ('d@gmail.com', 'x', 'y');
INSERT INTO "C##EBIPANI"."CUSTOMER" VALUES ('e@gmail.com', 'b', 'bb');
INSERT INTO "C##EBIPANI"."CUSTOMER" VALUES ('f@gmail.com', 'c', 'cc');

-- ----------------------------
-- Table structure for DJANGO_ADMIN_LOG
-- ----------------------------
DROP TABLE "C##EBIPANI"."DJANGO_ADMIN_LOG";
CREATE TABLE "C##EBIPANI"."DJANGO_ADMIN_LOG" (
  "ID" NUMBER(11,0) VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_78640".nextval NOT NULL,
  "ACTION_TIME" TIMESTAMP(6) VISIBLE NOT NULL,
  "OBJECT_ID" NCLOB VISIBLE,
  "OBJECT_REPR" NVARCHAR2(200) VISIBLE,
  "ACTION_FLAG" NUMBER(11,0) VISIBLE NOT NULL,
  "CHANGE_MESSAGE" NCLOB VISIBLE,
  "CONTENT_TYPE_ID" NUMBER(11,0) VISIBLE,
  "USER_ID" NUMBER(11,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DJANGO_ADMIN_LOG
-- ----------------------------

-- ----------------------------
-- Table structure for DJANGO_CONTENT_TYPE
-- ----------------------------
DROP TABLE "C##EBIPANI"."DJANGO_CONTENT_TYPE";
CREATE TABLE "C##EBIPANI"."DJANGO_CONTENT_TYPE" (
  "ID" NUMBER(11,0) VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_78605".nextval NOT NULL,
  "APP_LABEL" NVARCHAR2(100) VISIBLE,
  "MODEL" NVARCHAR2(100) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DJANGO_CONTENT_TYPE
-- ----------------------------
INSERT INTO "C##EBIPANI"."DJANGO_CONTENT_TYPE" VALUES ('1', 'admin', 'logentry');
INSERT INTO "C##EBIPANI"."DJANGO_CONTENT_TYPE" VALUES ('2', 'auth', 'permission');
INSERT INTO "C##EBIPANI"."DJANGO_CONTENT_TYPE" VALUES ('3', 'auth', 'group');
INSERT INTO "C##EBIPANI"."DJANGO_CONTENT_TYPE" VALUES ('4', 'auth', 'user');
INSERT INTO "C##EBIPANI"."DJANGO_CONTENT_TYPE" VALUES ('5', 'contenttypes', 'contenttype');
INSERT INTO "C##EBIPANI"."DJANGO_CONTENT_TYPE" VALUES ('6', 'sessions', 'session');

-- ----------------------------
-- Table structure for DJANGO_MIGRATIONS
-- ----------------------------
DROP TABLE "C##EBIPANI"."DJANGO_MIGRATIONS";
CREATE TABLE "C##EBIPANI"."DJANGO_MIGRATIONS" (
  "ID" NUMBER(19,0) VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_78602".nextval NOT NULL,
  "APP" NVARCHAR2(255) VISIBLE,
  "NAME" NVARCHAR2(255) VISIBLE,
  "APPLIED" TIMESTAMP(6) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DJANGO_MIGRATIONS
-- ----------------------------
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('1', 'contenttypes', '0001_initial', TO_TIMESTAMP('2022-02-04 12:20:42.226259', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('2', 'auth', '0001_initial', TO_TIMESTAMP('2022-02-04 12:20:43.229338', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('3', 'admin', '0001_initial', TO_TIMESTAMP('2022-02-04 12:20:43.421289', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('4', 'admin', '0002_logentry_remove_auto_add', TO_TIMESTAMP('2022-02-04 12:20:43.455932', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('5', 'admin', '0003_logentry_add_action_flag_choices', TO_TIMESTAMP('2022-02-04 12:20:43.480768', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('6', 'contenttypes', '0002_remove_content_type_name', TO_TIMESTAMP('2022-02-04 12:20:44.319524', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('7', 'auth', '0002_alter_permission_name_max_length', TO_TIMESTAMP('2022-02-04 12:20:44.407665', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('8', 'auth', '0003_alter_user_email_max_length', TO_TIMESTAMP('2022-02-04 12:20:44.453194', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('9', 'auth', '0004_alter_user_username_opts', TO_TIMESTAMP('2022-02-04 12:20:44.476894', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('10', 'auth', '0005_alter_user_last_login_null', TO_TIMESTAMP('2022-02-04 12:20:44.510854', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('11', 'auth', '0006_require_contenttypes_0002', TO_TIMESTAMP('2022-02-04 12:20:44.529996', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('12', 'auth', '0007_alter_validators_add_error_messages', TO_TIMESTAMP('2022-02-04 12:20:44.554638', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('13', 'auth', '0008_alter_user_username_max_length', TO_TIMESTAMP('2022-02-04 12:20:44.585755', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('14', 'auth', '0009_alter_user_last_name_max_length', TO_TIMESTAMP('2022-02-04 12:20:44.616436', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('15', 'auth', '0010_alter_group_name_max_length', TO_TIMESTAMP('2022-02-04 12:20:44.648540', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('16', 'auth', '0011_update_proxy_permissions', TO_TIMESTAMP('2022-02-04 12:20:44.672523', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('17', 'auth', '0012_alter_user_first_name_max_length', TO_TIMESTAMP('2022-02-04 12:20:44.703447', 'SYYYY-MM-DD HH24:MI:SS:FF6'));
INSERT INTO "C##EBIPANI"."DJANGO_MIGRATIONS" VALUES ('18', 'sessions', '0001_initial', TO_TIMESTAMP('2022-02-04 12:20:44.805653', 'SYYYY-MM-DD HH24:MI:SS:FF6'));

-- ----------------------------
-- Table structure for DJANGO_SESSION
-- ----------------------------
DROP TABLE "C##EBIPANI"."DJANGO_SESSION";
CREATE TABLE "C##EBIPANI"."DJANGO_SESSION" (
  "SESSION_KEY" NVARCHAR2(40) VISIBLE NOT NULL,
  "SESSION_DATA" NCLOB VISIBLE,
  "EXPIRE_DATE" TIMESTAMP(6) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DJANGO_SESSION
-- ----------------------------
INSERT INTO "C##EBIPANI"."DJANGO_SESSION" VALUES ('jyvz4e4yz4kpe7vino7sum7mh6lnda2e', 'e30:1nMU4g:5uU5ZSlDVcl_Xze1MCVbfbyL9ngmuqhWMb854rxa7Jk', TO_TIMESTAMP('2022-03-08 12:15:22.937820', 'SYYYY-MM-DD HH24:MI:SS:FF6'));

-- ----------------------------
-- Table structure for ORDERS
-- ----------------------------
DROP TABLE "C##EBIPANI"."ORDERS";
CREATE TABLE "C##EBIPANI"."ORDERS" (
  "CUSTOMER_EMAIL" VARCHAR2(320 BYTE) VISIBLE NOT NULL,
  "PRODUCT_ID" NUMBER VISIBLE NOT NULL,
  "ORDER_ID" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ORDERS
-- ----------------------------
INSERT INTO "C##EBIPANI"."ORDERS" VALUES ('d@gmail.com', '2', '6');
INSERT INTO "C##EBIPANI"."ORDERS" VALUES ('d@gmail.com', '2', '21');
INSERT INTO "C##EBIPANI"."ORDERS" VALUES ('d@gmail.com', '3', '21');
INSERT INTO "C##EBIPANI"."ORDERS" VALUES ('d@gmail.com', '8', '41');
INSERT INTO "C##EBIPANI"."ORDERS" VALUES ('d@gmail.com', '2', '43');
INSERT INTO "C##EBIPANI"."ORDERS" VALUES ('e@gmail.com', '5', '61');
INSERT INTO "C##EBIPANI"."ORDERS" VALUES ('d@gmail.com', '3', '3');
INSERT INTO "C##EBIPANI"."ORDERS" VALUES ('d@gmail.com', '5', '4');

-- ----------------------------
-- Table structure for ORDER_DETAILS
-- ----------------------------
DROP TABLE "C##EBIPANI"."ORDER_DETAILS";
CREATE TABLE "C##EBIPANI"."ORDER_DETAILS" (
  "ORDER_ID" NUMBER VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_76828".nextval NOT NULL,
  "ORDER_DATE" DATE VISIBLE NOT NULL,
  "DELIVERY_DATE" DATE VISIBLE NOT NULL,
  "SHIPPED_DATE" DATE VISIBLE NOT NULL,
  "PAYMENT_TYPE" VARCHAR2(16 BYTE) VISIBLE NOT NULL,
  "DELIVERY_ADDRESS" VARCHAR2(512 BYTE) VISIBLE NOT NULL,
  "CUSTOMER_EMAIL" VARCHAR2(320 BYTE) VISIBLE NOT NULL,
  "TRANSACTION_ID" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "BKASH_NO" NUMBER(11,0) VISIBLE NOT NULL,
  "SHIPPER_ID" NUMBER VISIBLE NOT NULL,
  "TOTAL_PRICE" NUMBER VISIBLE NOT NULL,
  "STATUS" VARCHAR2(29 BYTE) VISIBLE,
  "POSTAL_CODE" NUMBER VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of ORDER_DETAILS
-- ----------------------------
INSERT INTO "C##EBIPANI"."ORDER_DETAILS" VALUES ('6', TO_DATE('2022-02-18 13:49:45', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-03-05 13:49:45', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-02-21 13:49:45', 'SYYYY-MM-DD HH24:MI:SS'), 'BKASH', 'sdf', 'd@gmail.com', 'asdfE', '1111111111', '2', '400', 'PENDING', '1111');
INSERT INTO "C##EBIPANI"."ORDER_DETAILS" VALUES ('21', TO_DATE('2022-02-19 08:04:28', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-03-06 08:04:28', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-02-22 08:04:28', 'SYYYY-MM-DD HH24:MI:SS'), 'BKASH', 'dfgh', 'd@gmail.com', 'AD', '1111111111', '2', '300', 'PENDING', '1111');
INSERT INTO "C##EBIPANI"."ORDER_DETAILS" VALUES ('41', TO_DATE('2022-02-19 19:21:38', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-03-06 19:21:38', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-02-22 19:21:38', 'SYYYY-MM-DD HH24:MI:SS'), 'BKASH', 'uihg', 'd@gmail.com', 'dfghjk', '1111111111', '2', '23', 'PENDING', '1111');
INSERT INTO "C##EBIPANI"."ORDER_DETAILS" VALUES ('43', TO_DATE('2022-02-19 19:28:29', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-03-06 19:28:29', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-02-22 19:28:29', 'SYYYY-MM-DD HH24:MI:SS'), 'BKASH', 'asdf', 'd@gmail.com', 'asdgfhnmh', '1111111111', '2', '100', 'PENDING', '1111');
INSERT INTO "C##EBIPANI"."ORDER_DETAILS" VALUES ('61', TO_DATE('2022-02-21 22:05:02', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-03-08 22:05:02', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-02-24 22:05:02', 'SYYYY-MM-DD HH24:MI:SS'), 'BKASH', 'ASDF', 'e@gmail.com', 'ASDFGFH', '1111111111', '2', '168000', 'PENDING', '1111');
INSERT INTO "C##EBIPANI"."ORDER_DETAILS" VALUES ('3', TO_DATE('2022-02-18 08:51:42', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-03-05 08:51:42', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-02-21 08:51:42', 'SYYYY-MM-DD HH24:MI:SS'), 'BKASH', 'sadf', 'd@gmail.com', '23', '1111111111', '2', '100', 'APPROVED', '1111');
INSERT INTO "C##EBIPANI"."ORDER_DETAILS" VALUES ('4', TO_DATE('2022-02-18 08:52:42', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-03-05 08:52:42', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-02-21 08:52:42', 'SYYYY-MM-DD HH24:MI:SS'), 'BKASH', 'zdf', 'd@gmail.com', '43', '1111111111', '2', '56000', 'PENDING', '1111');
INSERT INTO "C##EBIPANI"."ORDER_DETAILS" VALUES ('5', TO_DATE('2022-02-18 08:53:00', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-03-05 08:53:00', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2022-02-21 08:53:00', 'SYYYY-MM-DD HH24:MI:SS'), 'BKASH', 'zdf', 'd@gmail.com', '1', '1111111111', '2', '0', 'PENDING', '1111');

-- ----------------------------
-- Table structure for PRODUCT
-- ----------------------------
DROP TABLE "C##EBIPANI"."PRODUCT";
CREATE TABLE "C##EBIPANI"."PRODUCT" (
  "PRODUCT_ID" NUMBER VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_76818".nextval NOT NULL,
  "CATEGORY_NAME" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "PRODUCT_NAME" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "UNIT_PRICE" NUMBER(10,2) VISIBLE NOT NULL,
  "UNITS_IN_STOCK" NUMBER(5,0) VISIBLE,
  "UNITS_ON_ORDER" NUMBER(5,0) VISIBLE,
  "IMAGE" VARCHAR2(256 BYTE) VISIBLE,
  "DESCRIPTION" VARCHAR2(256 BYTE) VISIBLE,
  "SELLER_EMAIL" VARCHAR2(320 BYTE) VISIBLE NOT NULL,
  "SUB_CATEGORY" VARCHAR2(250 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of PRODUCT
-- ----------------------------
INSERT INTO "C##EBIPANI"."PRODUCT" VALUES ('2', 'Electronic Devices', 'Samsung A52s', '100', '0', '108', '/static/img/Samsung A52s.jpg', NULL, 'a@gmail.com', 'mobile');
INSERT INTO "C##EBIPANI"."PRODUCT" VALUES ('3', 'Electronic Devices', 'iPhone 13 mini', '100', '0', '11', '/static/img/iPhone 13 mini.jpg', NULL, 'a@gmail.com', 'mobile');
INSERT INTO "C##EBIPANI"."PRODUCT" VALUES ('5', 'Electronic Devices', 'iPad Air 4', '56000', '82', '19', '/static/img/iPad Air 4.jpg', NULL, 'b@gmail.com', 'tablet');
INSERT INTO "C##EBIPANI"."PRODUCT" VALUES ('6', 'Groceries', 'bourbon', '10', '201', '0', '/static/img/Biscuit.jpg', NULL, 'c@gmail.com', 'biscuit');
INSERT INTO "C##EBIPANI"."PRODUCT" VALUES ('8', 'Groceries', 'dairy milk silk', '23', '23', '1', '/static/img/chocolate.jpg', NULL, 'c@gmail.com', 'chocolate');

-- ----------------------------
-- Table structure for REVIEW
-- ----------------------------
DROP TABLE "C##EBIPANI"."REVIEW";
CREATE TABLE "C##EBIPANI"."REVIEW" (
  "CUSTOMER_EMAIL" VARCHAR2(320 BYTE) VISIBLE NOT NULL,
  "PRODUCT_ID" NUMBER VISIBLE NOT NULL,
  "RATING" NUMBER VISIBLE,
  "CUSTOMER_COMMENT" VARCHAR2(256 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of REVIEW
-- ----------------------------
INSERT INTO "C##EBIPANI"."REVIEW" VALUES ('d@gmail.com', '2', '4', 'Too good');
INSERT INTO "C##EBIPANI"."REVIEW" VALUES ('d@gmail.com', '5', '3', 'Good product');

-- ----------------------------
-- Table structure for SELECTS
-- ----------------------------
DROP TABLE "C##EBIPANI"."SELECTS";
CREATE TABLE "C##EBIPANI"."SELECTS" (
  "PRODUCT_ID" NUMBER VISIBLE NOT NULL,
  "CUSTOMER_EMAIL" VARCHAR2(320 BYTE) VISIBLE NOT NULL,
  "TOTAL_UNIT" NUMBER VISIBLE,
  "STATUS" VARCHAR2(16 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of SELECTS
-- ----------------------------
INSERT INTO "C##EBIPANI"."SELECTS" VALUES ('2', 'd@gmail.com', '4', '6');
INSERT INTO "C##EBIPANI"."SELECTS" VALUES ('2', 'd@gmail.com', '1', '21');
INSERT INTO "C##EBIPANI"."SELECTS" VALUES ('3', 'f@gmail.com', '1', 'SELECTED');
INSERT INTO "C##EBIPANI"."SELECTS" VALUES ('3', 'd@gmail.com', '2', '21');
INSERT INTO "C##EBIPANI"."SELECTS" VALUES ('3', 'd@gmail.com', '1', '3');
INSERT INTO "C##EBIPANI"."SELECTS" VALUES ('5', 'd@gmail.com', '1', '4');
INSERT INTO "C##EBIPANI"."SELECTS" VALUES ('2', 'd@gmail.com', '1', '43');
INSERT INTO "C##EBIPANI"."SELECTS" VALUES ('5', 'e@gmail.com', '3', '61');
INSERT INTO "C##EBIPANI"."SELECTS" VALUES ('8', 'd@gmail.com', '1', '41');

-- ----------------------------
-- Table structure for SELLER
-- ----------------------------
DROP TABLE "C##EBIPANI"."SELLER";
CREATE TABLE "C##EBIPANI"."SELLER" (
  "EMAIL" VARCHAR2(320 BYTE) VISIBLE NOT NULL,
  "SHOP_NAME" VARCHAR2(64 BYTE) VISIBLE NOT NULL,
  "REGISTRATION_NO" VARCHAR2(64 BYTE) VISIBLE NOT NULL,
  "BKASH_NO" NUMBER(11,0) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of SELLER
-- ----------------------------
INSERT INTO "C##EBIPANI"."SELLER" VALUES ('a@gmail.com', 'a', 'xyz', '1111111111');
INSERT INTO "C##EBIPANI"."SELLER" VALUES ('b@gmail.com', 'b', 'bbb', '12');
INSERT INTO "C##EBIPANI"."SELLER" VALUES ('c@gmail.com', 'c', 'ccc', '123');

-- ----------------------------
-- Table structure for SHIPPER
-- ----------------------------
DROP TABLE "C##EBIPANI"."SHIPPER";
CREATE TABLE "C##EBIPANI"."SHIPPER" (
  "SHIPPER_ID" NUMBER VISIBLE DEFAULT "C##EBIPANI"."ISEQ$$_76823".nextval NOT NULL,
  "COMPANY_NAME" VARCHAR2(32 BYTE) VISIBLE NOT NULL,
  "PHONE" NUMBER(11,0) VISIBLE NOT NULL,
  "POSTAL_CODE" NUMBER VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of SHIPPER
-- ----------------------------
INSERT INTO "C##EBIPANI"."SHIPPER" VALUES ('2', 'DUMMY', '1234567890', '1111');

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "C##EBIPANI"."USERS";
CREATE TABLE "C##EBIPANI"."USERS" (
  "EMAIL" VARCHAR2(320 BYTE) VISIBLE NOT NULL,
  "PASSWORD" VARCHAR2(64 BYTE) VISIBLE NOT NULL,
  "PHONE" NUMBER(11,0) VISIBLE NOT NULL,
  "CITY" VARCHAR2(10 BYTE) VISIBLE,
  "COUNTRY" VARCHAR2(10 BYTE) VISIBLE,
  "POSTAL_CODE" NUMBER(10,0) VISIBLE,
  "ROLE" VARCHAR2(10 BYTE) VISIBLE NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of USERS
-- ----------------------------
INSERT INTO "C##EBIPANI"."USERS" VALUES ('amit1@gmail.com', '648767217', '1111456111', NULL, NULL, NULL, 'Admin');
INSERT INTO "C##EBIPANI"."USERS" VALUES ('amit@gmail.com', '110593', '1234', 'a', 'b', '1', 'Admin');
INSERT INTO "C##EBIPANI"."USERS" VALUES ('s@gmail.com', '648767217', '1111111111', 'ctg', 'basf', '1111', 'Customer');
INSERT INTO "C##EBIPANI"."USERS" VALUES ('a@gmail.com', '115058', '1234567890', 'a', 'b', '1000', 'Seller');
INSERT INTO "C##EBIPANI"."USERS" VALUES ('b@gmail.com', '5513854', '12', 'a', 'b', '1', 'Seller');
INSERT INTO "C##EBIPANI"."USERS" VALUES ('c@gmail.com', '264136947', '123', 'a', 'b', '1', 'Seller');
INSERT INTO "C##EBIPANI"."USERS" VALUES ('d@gmail.com', '110593', '1234567891', 'Ctg', 'BGD', '1611', 'Customer');
INSERT INTO "C##EBIPANI"."USERS" VALUES ('e@gmail.com', '5197920', '1112', 'a', 'b', '1', 'Customer');
INSERT INTO "C##EBIPANI"."USERS" VALUES ('f@gmail.com', '244302289', '12345', 'a', 'b', '1', 'Customer');

-- ----------------------------
-- Table structure for test
-- ----------------------------
DROP TABLE "C##EBIPANI"."test";
CREATE TABLE "C##EBIPANI"."test" (
  "ID" NUMBER VISIBLE NOT NULL,
  "Name" VARCHAR2(255 BYTE) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of test
-- ----------------------------
INSERT INTO "C##EBIPANI"."test" VALUES ('1', 'amit');
INSERT INTO "C##EBIPANI"."test" VALUES ('2', 'sumonta');
INSERT INTO "C##EBIPANI"."test" VALUES ('3', 'nandy');

-- ----------------------------
-- Function structure for ADD_TO_CART
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "C##EBIPANI"."ADD_TO_CART" AS
BEGIN 
	SELECT COUNT(*) INTO N 
	FROM SELECTS 
	WHERE CUSTOMER_EMAIL = MAIL AND PRODUCT_ID = PID AND UPPER(STATUS) = 'SELECTED';
	
	IF N > 0 THEN
		SELECT TOTAL_UNIT INTO N 
		FROM SELECTS 
		WHERE CUSTOMER_EMAIL = MAIL AND PRODUCT_ID = PID AND UPPER(STATUS) = 'SELECTED';
		
		UPDATE SELECTS 
		SET TOTAL_UNIT = N + 1
		WHERE CUSTOMER_EMAIL = MAIL AND PRODUCT_ID = PID AND UPPER(STATUS) = 'SELECTED';
	ELSE 
		INSERT INTO SELECTS
		VALUES(PID, MAIL, 1, 'SELECTED');
	END IF;
END;
/

-- ----------------------------
-- Function structure for GET_PRODUCT_NAME
-- ----------------------------
CREATE OR REPLACE
FUNCTION "C##EBIPANI"."GET_PRODUCT_NAME" AS
BEGIN
	SELECT PRODUCT_NAME INTO NAME 
	FROM PRODUCT 
	WHERE PRODUCT_ID = PID; 
	RETURN NAME;
END;
/

-- ----------------------------
-- Function structure for GET_ROLE
-- ----------------------------
CREATE OR REPLACE
FUNCTION "C##EBIPANI"."GET_ROLE" AS
BEGIN 
	SELECT UPPER(ROLE) INTO UROLE
	FROM USERS
	WHERE EMAIL = MAIL;
	
	RETURN UROLE;
END;
/

-- ----------------------------
-- Function structure for GET_SELLER_EMAIL
-- ----------------------------
CREATE OR REPLACE
FUNCTION "C##EBIPANI"."GET_SELLER_EMAIL" AS
BEGIN 
	SELECT SELLER_EMAIL INTO MAIL
	FROM PRODUCT 
	WHERE PRODUCT_ID = PID;
	
	RETURN MAIL;
END;
/

-- ----------------------------
-- Function structure for IN_STOCK
-- ----------------------------
CREATE OR REPLACE
FUNCTION "C##EBIPANI"."IN_STOCK" AS
BEGIN 
	FLAG := 0;
	FOR R IN (SELECT
							S.PRODUCT_ID AS PID,
							S.TOTAL_UNIT AS TU 
						FROM
							SELECTS S 
						WHERE
							S.CUSTOMER_EMAIL = CE 
							AND UPPER( STATUS ) = 'SELECTED' 
							AND S.PRODUCT_ID IN ( SELECT PRODUCT_ID FROM PRODUCT WHERE SELLER_EMAIL = SE ))
	LOOP 
		SELECT UNITS_IN_STOCK INTO N 
		FROM PRODUCT 
		WHERE PRODUCT_ID=R.PID;
		
		IF R.TU > N THEN 
			FLAG := R.PID;
			EXIT;
		END IF;
	END LOOP;

	IF FLAG = 0 THEN
		FOR R IN (SELECT
								S.PRODUCT_ID AS PID,
								S.TOTAL_UNIT AS TU 
							FROM
								SELECTS S 
							WHERE
								S.CUSTOMER_EMAIL = CE 
								AND UPPER( STATUS ) = 'SELECTED' 
								AND S.PRODUCT_ID IN ( SELECT PRODUCT_ID FROM PRODUCT WHERE SELLER_EMAIL = SE ))
		LOOP 
			UPDATE PRODUCT 
			SET UNITS_IN_STOCK = UNITS_IN_STOCK - R.TU,
					UNITS_ON_ORDER = UNITS_ON_ORDER + R.TU 
			WHERE PRODUCT.PRODUCT_ID = R.PID;
		END LOOP;
	END IF;
	
	RETURN FLAG;
END;
/

-- ----------------------------
-- Function structure for REVERT_STOCK
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "C##EBIPANI"."REVERT_STOCK" AS
BEGIN 
	FOR R IN (SELECT
							S.PRODUCT_ID AS PID,
							S.TOTAL_UNIT AS TU 
						FROM
							SELECTS S 
						WHERE
							S.CUSTOMER_EMAIL = CE 
							AND UPPER( STATUS ) = 'SELECTED' 
							AND S.PRODUCT_ID IN ( SELECT PRODUCT_ID FROM PRODUCT WHERE SELLER_EMAIL = SE ))
	LOOP 
		UPDATE PRODUCT 
		SET UNITS_IN_STOCK = UNITS_IN_STOCK + R.TU,
				UNITS_ON_ORDER = UNITS_ON_ORDER - R.TU 
		WHERE PRODUCT.PRODUCT_ID = R.PID;
	END LOOP;
END;
/

-- ----------------------------
-- Function structure for SET_STATUS_IN_SELECTS
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "C##EBIPANI"."SET_STATUS_IN_SELECTS" AS
BEGIN
	UPDATE SELECTS 
	SET STATUS='PAID' 
	WHERE CUSTOMER_EMAIL=CE AND UPPER(STATUS)='SELECTED' AND PRODUCT_ID IN (SELECT PRODUCT_ID FROM PRODUCT WHERE SELLER_EMAIL=SE);
END;
/

-- ----------------------------
-- Function structure for UPDATE_RATING_REVIEW
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "C##EBIPANI"."UPDATE_RATING_REVIEW" AS
BEGIN
	SELECT COUNT(CUSTOMER_EMAIL) INTO N 
	FROM REVIEW 
	WHERE CUSTOMER_EMAIL = MAIL AND PRODUCT_ID = TO_NUMBER(PID);
	
	IF N > 0 THEN	
		IF UPPER(MSG) = 'RATING' THEN
			UPDATE REVIEW
			SET RATING = TO_NUMBER(VALUE)
			WHERE CUSTOMER_EMAIL = MAIL AND PRODUCT_ID = TO_NUMBER(PID);
		ELSE
			UPDATE REVIEW
			SET CUSTOMER_COMMENT = VALUE
			WHERE CUSTOMER_EMAIL = MAIL AND PRODUCT_ID = TO_NUMBER(PID);
		END IF;
		
	ELSE
		IF UPPER(MSG) = 'RATING' THEN
			INSERT INTO REVIEW(CUSTOMER_EMAIL, PRODUCT_ID, RATING)
			VALUES(MAIL, PID, TO_NUMBER(VALUE));
		ELSE
			INSERT INTO REVIEW(CUSTOMER_EMAIL, PRODUCT_ID, CUSTOMER_COMMENT)
			VALUES(MAIL, PID, VALUE);
		END IF;
	
	END IF;
	
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('ERROR');
		
END;
/

-- ----------------------------
-- Function structure for UPDATE_STOCK
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "C##EBIPANI"."UPDATE_STOCK" AS
BEGIN 
	FOR R IN (SELECT
							S.PRODUCT_ID AS PID,
							S.TOTAL_UNIT AS TU 
						FROM
							SELECTS S 
						WHERE
							S.CUSTOMER_EMAIL = CE 
							AND UPPER( STATUS ) = 'SELECTED' 
							AND S.PRODUCT_ID IN ( SELECT PRODUCT_ID FROM PRODUCT WHERE SELLER_EMAIL = SE ))
	LOOP 
		UPDATE PRODUCT 
		SET UNITS_IN_STOCK = UNITS_IN_STOCK + R.TU,
				UNITS_ON_ORDER = UNITS_ON_ORDER - R.TU 
		WHERE PRODUCT.PRODUCT_ID = R.PID;
	END LOOP;
END;
/

-- ----------------------------
-- Function structure for USER_AUTHENTICATION
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "C##EBIPANI"."USER_AUTHENTICATION" AS
BEGIN
	SELECT COUNT(*) INTO no
	FROM C##EBIPANI.USERS 
	WHERE EMAIL = mail AND PASSWORD = pass;
END;
/

-- ----------------------------
-- Sequence structure for ISEQ$$_76772
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_76772";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_76772" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_76777
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_76777";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_76777" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_76784
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_76784";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_76784" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_76795
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_76795";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_76795" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_76800
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_76800";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_76800" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_76805
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_76805";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_76805" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_76818
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_76818";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_76818" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_76823
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_76823";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_76823" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_76828
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_76828";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_76828" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_78602
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_78602";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_78602" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_78605
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_78605";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_78605" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_78609
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_78609";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_78609" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_78612
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_78612";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_78612" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_78616
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_78616";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_78616" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_78619
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_78619";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_78619" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_78623
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_78623";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_78623" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_78626
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_78626";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_78626" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for ISEQ$$_78640
-- ----------------------------
DROP SEQUENCE "C##EBIPANI"."ISEQ$$_78640";
CREATE SEQUENCE "C##EBIPANI"."ISEQ$$_78640" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table AUTH_GROUP
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_GROUP" ADD CONSTRAINT "SYS_C008171" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_GROUP
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_GROUP" ADD CONSTRAINT "SYS_C008172" UNIQUE ("NAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_GROUP
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_GROUP" ADD CONSTRAINT "SYS_C008170" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table AUTH_GROUP_PERMISSIONS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "SYS_C008176" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_GROUP_PERMISSIONS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "AUTH_GROU_GROUP_ID__0CD325B0_U" UNIQUE ("GROUP_ID", "PERMISSION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_GROUP_PERMISSIONS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "SYS_C008173" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "SYS_C008174" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_GROUP_PERMISSIONS" ADD CONSTRAINT "SYS_C008175" CHECK ("PERMISSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table AUTH_GROUP_PERMISSIONS
-- ----------------------------
CREATE INDEX "C##EBIPANI"."AUTH_GROUP_GROUP_ID_B120CBF9"
  ON "C##EBIPANI"."AUTH_GROUP_PERMISSIONS" ("GROUP_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "C##EBIPANI"."AUTH_GROUP_PERMISSION_84C5C92E"
  ON "C##EBIPANI"."AUTH_GROUP_PERMISSIONS" ("PERMISSION_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table AUTH_PERMISSION
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_PERMISSION" ADD CONSTRAINT "SYS_C008169" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_PERMISSION
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_PERMISSION" ADD CONSTRAINT "AUTH_PERM_CONTENT_T_01AB375A_U" UNIQUE ("CONTENT_TYPE_ID", "CODENAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_PERMISSION
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_PERMISSION" ADD CONSTRAINT "SYS_C008167" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_PERMISSION" ADD CONSTRAINT "SYS_C008168" CHECK ("CONTENT_TYPE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table AUTH_PERMISSION
-- ----------------------------
CREATE INDEX "C##EBIPANI"."AUTH_PERMI_CONTENT_TY_2F476E4B"
  ON "C##EBIPANI"."AUTH_PERMISSION" ("CONTENT_TYPE_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table AUTH_USER
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_USER" ADD CONSTRAINT "SYS_C008186" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_USER
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_USER" ADD CONSTRAINT "SYS_C008187" UNIQUE ("USERNAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_USER
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_USER" ADD CONSTRAINT "SYS_C008177" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_USER" ADD CONSTRAINT "SYS_C008179" CHECK ("IS_SUPERUSER" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_USER" ADD CONSTRAINT "SYS_C008180" CHECK ("IS_STAFF" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_USER" ADD CONSTRAINT "SYS_C008181" CHECK ("IS_ACTIVE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_USER" ADD CONSTRAINT "SYS_C008182" CHECK ("DATE_JOINED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_USER" ADD CONSTRAINT "SYS_C008183" CHECK ("IS_SUPERUSER" IN (0,1)) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_USER" ADD CONSTRAINT "SYS_C008184" CHECK ("IS_STAFF" IN (0,1)) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_USER" ADD CONSTRAINT "SYS_C008185" CHECK ("IS_ACTIVE" IN (0,1)) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table AUTH_USER_GROUPS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_USER_GROUPS" ADD CONSTRAINT "SYS_C008191" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_USER_GROUPS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_USER_GROUPS" ADD CONSTRAINT "AUTH_USER_USER_ID_G_94350C0C_U" UNIQUE ("USER_ID", "GROUP_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_USER_GROUPS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_USER_GROUPS" ADD CONSTRAINT "SYS_C008188" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_USER_GROUPS" ADD CONSTRAINT "SYS_C008189" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_USER_GROUPS" ADD CONSTRAINT "SYS_C008190" CHECK ("GROUP_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table AUTH_USER_GROUPS
-- ----------------------------
CREATE INDEX "C##EBIPANI"."AUTH_USER__GROUP_ID_97559544"
  ON "C##EBIPANI"."AUTH_USER_GROUPS" ("GROUP_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "C##EBIPANI"."AUTH_USER__USER_ID_6A12ED8B"
  ON "C##EBIPANI"."AUTH_USER_GROUPS" ("USER_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table AUTH_USER_USER_PERMISSIONS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "SYS_C008195" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table AUTH_USER_USER_PERMISSIONS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "AUTH_USER_USER_ID_P_14A6B632_U" UNIQUE ("USER_ID", "PERMISSION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table AUTH_USER_USER_PERMISSIONS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "SYS_C008192" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "SYS_C008193" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."AUTH_USER_USER_PERMISSIONS" ADD CONSTRAINT "SYS_C008194" CHECK ("PERMISSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table AUTH_USER_USER_PERMISSIONS
-- ----------------------------
CREATE INDEX "C##EBIPANI"."AUTH_USER__PERMISSION_1FBB5F2C"
  ON "C##EBIPANI"."AUTH_USER_USER_PERMISSIONS" ("PERMISSION_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "C##EBIPANI"."AUTH_USER__USER_ID_A95EAD1B"
  ON "C##EBIPANI"."AUTH_USER_USER_PERMISSIONS" ("USER_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table CATEGORY
-- ----------------------------
ALTER TABLE "C##EBIPANI"."CATEGORY" ADD CONSTRAINT "PK_CN_CATEGORY" PRIMARY KEY ("CATEGORY_NAME");

-- ----------------------------
-- Checks structure for table CATEGORY
-- ----------------------------
ALTER TABLE "C##EBIPANI"."CATEGORY" ADD CONSTRAINT "SYS_C007956" CHECK ("CATEGORY_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table CUSTOMER
-- ----------------------------
ALTER TABLE "C##EBIPANI"."CUSTOMER" ADD CONSTRAINT "PK_EMAIL_CUSTOMER" PRIMARY KEY ("EMAIL");

-- ----------------------------
-- Checks structure for table CUSTOMER
-- ----------------------------
ALTER TABLE "C##EBIPANI"."CUSTOMER" ADD CONSTRAINT "SYS_C007953" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DJANGO_ADMIN_LOG
-- ----------------------------
ALTER TABLE "C##EBIPANI"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C008212" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table DJANGO_ADMIN_LOG
-- ----------------------------
ALTER TABLE "C##EBIPANI"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C008207" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C008208" CHECK ("ACTION_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C008209" CHECK ("ACTION_FLAG" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C008210" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."DJANGO_ADMIN_LOG" ADD CONSTRAINT "SYS_C008211" CHECK ("ACTION_FLAG" >= 0) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table DJANGO_ADMIN_LOG
-- ----------------------------
CREATE INDEX "C##EBIPANI"."DJANGO_ADM_CONTENT_TY_C4BCE8EB"
  ON "C##EBIPANI"."DJANGO_ADMIN_LOG" ("CONTENT_TYPE_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "C##EBIPANI"."DJANGO_ADM_USER_ID_C564EBA6"
  ON "C##EBIPANI"."DJANGO_ADMIN_LOG" ("USER_ID" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table DJANGO_CONTENT_TYPE
-- ----------------------------
ALTER TABLE "C##EBIPANI"."DJANGO_CONTENT_TYPE" ADD CONSTRAINT "SYS_C008165" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table DJANGO_CONTENT_TYPE
-- ----------------------------
ALTER TABLE "C##EBIPANI"."DJANGO_CONTENT_TYPE" ADD CONSTRAINT "DJANGO_CO_APP_LABEL_76BD3D3B_U" UNIQUE ("APP_LABEL", "MODEL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table DJANGO_CONTENT_TYPE
-- ----------------------------
ALTER TABLE "C##EBIPANI"."DJANGO_CONTENT_TYPE" ADD CONSTRAINT "SYS_C008164" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DJANGO_MIGRATIONS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."DJANGO_MIGRATIONS" ADD CONSTRAINT "SYS_C008163" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table DJANGO_MIGRATIONS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."DJANGO_MIGRATIONS" ADD CONSTRAINT "SYS_C008161" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."DJANGO_MIGRATIONS" ADD CONSTRAINT "SYS_C008162" CHECK ("APPLIED" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DJANGO_SESSION
-- ----------------------------
ALTER TABLE "C##EBIPANI"."DJANGO_SESSION" ADD CONSTRAINT "SYS_C008217" PRIMARY KEY ("SESSION_KEY");

-- ----------------------------
-- Checks structure for table DJANGO_SESSION
-- ----------------------------
ALTER TABLE "C##EBIPANI"."DJANGO_SESSION" ADD CONSTRAINT "SYS_C008215" CHECK ("SESSION_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."DJANGO_SESSION" ADD CONSTRAINT "SYS_C008216" CHECK ("EXPIRE_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table DJANGO_SESSION
-- ----------------------------
CREATE INDEX "C##EBIPANI"."DJANGO_SES_EXPIRE_DAT_A5C62663"
  ON "C##EBIPANI"."DJANGO_SESSION" ("EXPIRE_DATE" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Checks structure for table ORDERS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."ORDERS" ADD CONSTRAINT "SYS_C008278" CHECK ("CUSTOMER_EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDERS" ADD CONSTRAINT "SYS_C008279" CHECK ("PRODUCT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDERS" ADD CONSTRAINT "SYS_C008280" CHECK ("ORDER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table ORDER_DETAILS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "PK_OID_ORDER_DETAILS" PRIMARY KEY ("ORDER_ID");

-- ----------------------------
-- Uniques structure for table ORDER_DETAILS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "UNIQUE_TRANSACTION_ID" UNIQUE ("TRANSACTION_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table ORDER_DETAILS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C007981" CHECK ("ORDER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C007982" CHECK ("ORDER_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C007983" CHECK ("DELIVERY_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C007984" CHECK ("SHIPPED_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C007985" CHECK ("PAYMENT_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C007986" CHECK ("DELIVERY_ADDRESS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C007987" CHECK ("CUSTOMER_EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C007988" CHECK ("TRANSACTION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C007989" CHECK ("BKASH_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C007990" CHECK ("SHIPPER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C008284" CHECK ("TOTAL_PRICE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "SYS_C008289" CHECK ("POSTAL_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table ORDER_DETAILS
-- ----------------------------
CREATE TRIGGER "C##EBIPANI"."UPDATE_ORDER_DETAILS" AFTER INSERT ON "C##EBIPANI"."ORDER_DETAILS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
DECLARE 
	OID NUMBER;
	CE VARCHAR2(320);
	N NUMBER;
BEGIN 
	OID := :NEW.ORDER_ID;
	CE := :NEW.CUSTOMER_EMAIL;
	
	FOR R IN (SELECT S.PRODUCT_ID PID, S.TOTAL_UNIT TU 
						FROM SELECTS S
						WHERE S.CUSTOMER_EMAIL=CE AND UPPER(S.STATUS)='PAID') 
	LOOP 
		INSERT INTO ORDERS(CUSTOMER_EMAIL, PRODUCT_ID, ORDER_ID) 
		VALUES(CE, R.PID, OID);
		
		UPDATE SELECTS 
		SET STATUS = TO_CHAR(OID)
		WHERE CUSTOMER_EMAIL=CE AND UPPER(STATUS)='PAID' AND PRODUCT_ID=R.PID;
	END LOOP;
END;
/

-- ----------------------------
-- Primary Key structure for table PRODUCT
-- ----------------------------
ALTER TABLE "C##EBIPANI"."PRODUCT" ADD CONSTRAINT "PK_ID_PRODUCT" PRIMARY KEY ("PRODUCT_ID");

-- ----------------------------
-- Checks structure for table PRODUCT
-- ----------------------------
ALTER TABLE "C##EBIPANI"."PRODUCT" ADD CONSTRAINT "SYS_C007958" CHECK ("PRODUCT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."PRODUCT" ADD CONSTRAINT "SYS_C007959" CHECK ("CATEGORY_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."PRODUCT" ADD CONSTRAINT "SYS_C007960" CHECK ("PRODUCT_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."PRODUCT" ADD CONSTRAINT "SYS_C007961" CHECK ("UNIT_PRICE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."PRODUCT" ADD CONSTRAINT "SYS_C007962" CHECK ("SELLER_EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table REVIEW
-- ----------------------------
ALTER TABLE "C##EBIPANI"."REVIEW" ADD CONSTRAINT "PK_PID_CE_REVIEW" PRIMARY KEY ("PRODUCT_ID", "CUSTOMER_EMAIL");

-- ----------------------------
-- Checks structure for table REVIEW
-- ----------------------------
ALTER TABLE "C##EBIPANI"."REVIEW" ADD CONSTRAINT "SYS_C007976" CHECK ("CUSTOMER_EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."REVIEW" ADD CONSTRAINT "SYS_C007977" CHECK ("PRODUCT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table SELECTS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."SELECTS" ADD CONSTRAINT "SYS_C007966" CHECK ("PRODUCT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."SELECTS" ADD CONSTRAINT "SYS_C007967" CHECK ("CUSTOMER_EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."SELECTS" ADD CONSTRAINT "SYS_C007968" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table SELLER
-- ----------------------------
ALTER TABLE "C##EBIPANI"."SELLER" ADD CONSTRAINT "PK_EMAIL_SELLER" PRIMARY KEY ("EMAIL");

-- ----------------------------
-- Checks structure for table SELLER
-- ----------------------------
ALTER TABLE "C##EBIPANI"."SELLER" ADD CONSTRAINT "SYS_C007947" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."SELLER" ADD CONSTRAINT "SYS_C007948" CHECK ("SHOP_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."SELLER" ADD CONSTRAINT "SYS_C007949" CHECK ("REGISTRATION_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."SELLER" ADD CONSTRAINT "SYS_C007950" CHECK ("BKASH_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table SHIPPER
-- ----------------------------
ALTER TABLE "C##EBIPANI"."SHIPPER" ADD CONSTRAINT "PK_ID_SHIPPER" PRIMARY KEY ("SHIPPER_ID");

-- ----------------------------
-- Checks structure for table SHIPPER
-- ----------------------------
ALTER TABLE "C##EBIPANI"."SHIPPER" ADD CONSTRAINT "SYS_C007972" CHECK ("SHIPPER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."SHIPPER" ADD CONSTRAINT "SYS_C007973" CHECK ("COMPANY_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."SHIPPER" ADD CONSTRAINT "SYS_C007974" CHECK ("PHONE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table USERS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."USERS" ADD CONSTRAINT "PK_EMAIL_USERS" PRIMARY KEY ("EMAIL");

-- ----------------------------
-- Checks structure for table USERS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."USERS" ADD CONSTRAINT "SYS_C007942" CHECK ("EMAIL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."USERS" ADD CONSTRAINT "SYS_C007943" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."USERS" ADD CONSTRAINT "SYS_C007944" CHECK ("PHONE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."USERS" ADD CONSTRAINT "SYS_C007945" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table test
-- ----------------------------
ALTER TABLE "C##EBIPANI"."test" ADD CONSTRAINT "SYS_C007813" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table test
-- ----------------------------
ALTER TABLE "C##EBIPANI"."test" ADD CONSTRAINT "SYS_C007812" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table AUTH_GROUP_PERMISSIONS
-- ----------------------------

-- ----------------------------
-- Foreign Keys structure for table AUTH_PERMISSION
-- ----------------------------

-- ----------------------------
-- Foreign Keys structure for table AUTH_USER_GROUPS
-- ----------------------------

-- ----------------------------
-- Foreign Keys structure for table AUTH_USER_USER_PERMISSIONS
-- ----------------------------

-- ----------------------------
-- Foreign Keys structure for table CUSTOMER
-- ----------------------------
ALTER TABLE "C##EBIPANI"."CUSTOMER" ADD CONSTRAINT "FK_EMAIL_CUSTOMER" FOREIGN KEY ("EMAIL") REFERENCES "C##EBIPANI"."USERS" ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table DJANGO_ADMIN_LOG
-- ----------------------------

-- ----------------------------
-- Foreign Keys structure for table ORDERS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."ORDERS" ADD CONSTRAINT "FK_CE_ORDERS" FOREIGN KEY ("CUSTOMER_EMAIL") REFERENCES "C##EBIPANI"."CUSTOMER" ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDERS" ADD CONSTRAINT "FK_OID_ORDERS" FOREIGN KEY ("ORDER_ID") REFERENCES "C##EBIPANI"."ORDER_DETAILS" ("ORDER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDERS" ADD CONSTRAINT "FK_PID_ORDERS" FOREIGN KEY ("PRODUCT_ID") REFERENCES "C##EBIPANI"."PRODUCT" ("PRODUCT_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table ORDER_DETAILS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "FK_CE_ORDER_DETAILS" FOREIGN KEY ("CUSTOMER_EMAIL") REFERENCES "C##EBIPANI"."CUSTOMER" ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."ORDER_DETAILS" ADD CONSTRAINT "FK_SID_ORDER_DETAILS" FOREIGN KEY ("SHIPPER_ID") REFERENCES "C##EBIPANI"."SHIPPER" ("SHIPPER_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table PRODUCT
-- ----------------------------
ALTER TABLE "C##EBIPANI"."PRODUCT" ADD CONSTRAINT "FK_CN_PRODUCT" FOREIGN KEY ("CATEGORY_NAME") REFERENCES "C##EBIPANI"."CATEGORY" ("CATEGORY_NAME") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."PRODUCT" ADD CONSTRAINT "FK_SE_PRODUCT" FOREIGN KEY ("SELLER_EMAIL") REFERENCES "C##EBIPANI"."SELLER" ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table REVIEW
-- ----------------------------
ALTER TABLE "C##EBIPANI"."REVIEW" ADD CONSTRAINT "FK_CE_REVIEW" FOREIGN KEY ("CUSTOMER_EMAIL") REFERENCES "C##EBIPANI"."CUSTOMER" ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."REVIEW" ADD CONSTRAINT "FK_PID_REVIEW" FOREIGN KEY ("PRODUCT_ID") REFERENCES "C##EBIPANI"."PRODUCT" ("PRODUCT_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table SELECTS
-- ----------------------------
ALTER TABLE "C##EBIPANI"."SELECTS" ADD CONSTRAINT "FK_CE_SELECTS" FOREIGN KEY ("CUSTOMER_EMAIL") REFERENCES "C##EBIPANI"."CUSTOMER" ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "C##EBIPANI"."SELECTS" ADD CONSTRAINT "FK_PID_SELECTS" FOREIGN KEY ("PRODUCT_ID") REFERENCES "C##EBIPANI"."PRODUCT" ("PRODUCT_ID") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table SELLER
-- ----------------------------
ALTER TABLE "C##EBIPANI"."SELLER" ADD CONSTRAINT "FK_EMAIL_SELLER" FOREIGN KEY ("EMAIL") REFERENCES "C##EBIPANI"."USERS" ("EMAIL") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
